### ISSUE TITLE
Finding & rendering views fails when targeting net471

### ISSUE THREAD

**Issue by onionhammer** [aspnet/Home#3088]
Easily reproduce:

```
git clone https://github.com/onionhammer/Wivuu.RazorInline.git
cd Wivuu.RazorInline
dotnet test 
```

Should pass. Now change tests/tests.csproj to target net471 instead of netcoreapp2.0 and re-run the tests. This produces the following:

System.InvalidOperationException: Unable to find view 'ViewTest'. The following locations were searched:
/Views/ViewTest.cshtml
/Views/Shared/ViewTest.cshtml
/Pages/Shared/ViewTest.cshtml

@pranavkm This is related to https://github.com/aspnet/Razor/issues/2274#issuecomment-383738252

**Comment by pranavkm** [comment]
@onionhammer I can see the test fail in both TFMs. Not entirely sure why it works for you in `netcoreapp2.0`, but the primary issue is that you're pointing to the [current working directory](https://github.com/onionhammer/Wivuu.RazorInline/blob/master/razor-inline/StartupExtensions.cs#L28) which happens to be OutputDirectory of the project. You'll need to either have the Views directory be copied as content or point the content root to the test.views directory. 

* Once you're past that, you'll need to set `<PreserveCompilationContext>true</PreserveCompilationContext>` in the test project since you're doing runtime compilation. 
* Finally, on desktop, you'll need to ensure that the deps file is placed next to the binary. In xunit testing, this is usually done by turning off shadow copy, but there [doesn't seem](https://stackoverflow.com/questions/2413832/how-do-i-turn-off-shadow-copy-in-a-visual-studio-2010-test-project) to be an equivalent setting for MSTest. The recommendation there is to deploy the deps file found in `bin\Debug\net471\AppName.deps.json` along with the binary.

**Comment by onionhammer** [comment]
Jesus

**Comment by pranavkm** [comment]
> I'm actually trying to compile the views into the library assembly, and use them from tests.

Sounds like you're attempting to do build time compilation. You'd have to use the Razor Sdk (available as part of 2.1.0-preview2 or later). There's an announcement post about it here - https://blogs.msdn.microsoft.com/webdev/2018/04/12/asp-net-core-2-1-0-preview2-now-available. 

> Shouldn't the behavior be consistent between net471 and netcoreapp2.0

Apart from the shadow copying oddity (which is also addressed in 2.1.0 - see https://github.com/dotnet/core-setup/issues/3308), the requirements for runtime compilation, while cumbersome, are identical between the two  - have the right content root and have PreserveCompilationContext=true.

**Comment by onionhammer** [comment]
@pranavkm Yes, I am using the Razor SDK in the library, see https://github.com/onionhammer/Wivuu.RazorInline/blob/master/tests.views/tests.views.csproj#L1

**Comment by pranavkm** [comment]
@onionhammer feel free to reopen if you have still have questions.

**Comment by onionhammer** [comment]
@pranavkm Everything has been upgraded with the release of dotnet core 2.1.1; this issue is still present - this should not have been closed in the first place I suspect.

MSTest project tests pass if targeting netcoreapp2.1, but fail if targeting net471

**Comment by pranavkm** [comment]
> Application name is calculated using a directory path. In your tests, this defaults to Wivuu.RazorInline which does not reference tests.views. The application name must be an assembly that references tests.views. You might want to consider passing an application name explicitly rather than calculating it from the path.

Did you make this change?

**Comment by onionhammer** [comment]
@pranavkm No, but that is a workaround for the root issue; the behavior should be consistent between net471 and netcoreapp2.1

**Comment by pranavkm** [comment]
> No, but that is a workaround for the root issue

It's not a workaround, it's a requirement that the correct app name be set. I haven't investigated why it works in `netcoreapp`, but that wouldn't qualify as an issue.
