### ISSUE TITLE
SqlMetaData not supported in ASP.NET 5

### ISSUE THREAD

**Issue by radenkozec** [aspnet/Home#477]
I am trying to use SqlMetaData in ASP.NET 5. I am getting error that is not supported in ASP.NET 5 Core.

The type initializer for 'Microsoft.SqlServer.Server.SqlMetaData' threw an exception: Type Udt is not supported on this platform.
Is this issue fixed?

You can read more info here : http://stackoverflow.com/questions/29771047/sqlmetadata-not-supported-in-asp-net-5/29772451

**Comment by Eilon** [comment]
@divega @rowanmiller

**Comment by radenkozec** [comment]
@Eilon @divega @rowanmiller Any new info about this? 
I see this class is not included in beta4...

**Comment by rowanmiller** [comment]
@radenkozec I saw from your StackOverflow post that you were using 1.0.0-beta1 of SqlClient. Can you try out the latest release (4.0.0-beta-22816). beta1/beta2 were a top-gab prototype and the latest release is a proper implementation of SqlClient, so I suspect the issue is resolved.

**Comment by radenkozec** [comment]
@rowanmiller I currently use Visual Studio RC,upgraded to beta 4 still not working. 
I am still getting a exception:
The type initializer for 'Microsoft.SqlServer.Server.SqlMetaData' threw an exception: Type Udt is not supported on this platform.

It seams that class SqlMetaData is not ported to .NET Core SqlClient dll.
My project.json looks like this:

{
    "version": "1.0.0-*",
    "description": "",
    "authors": [ "" ],
    "tags": [ "" ],
    "projectUrl": "",
    "licenseUrl": "",

    "dependencies": {
        "Blade.Model": "1.0.0-*",
        "Microsoft.Framework.ConfigurationModel.Json": "1.0.0-beta4",
        "Microsoft.Net.Http.Client": "1.0.0.0-beta3-10053",
        "System.Data.Common": "4.0.0-beta-22816",
        "System.Data.SqlClient": "4.0.0-beta-22816",
        "Newtonsoft.Json": "7.0.1-beta3"
    },

    "frameworks": {
        "net451": {},
        "dnx451": { },
        "dnxcore50": {
            "dependencies": {
                "System.Collections": "4.0.10-beta-22816",
                "System.Runtime": "4.0.20-beta-22816"
            }
        }
    }
}

**Comment by rowanmiller** [comment]
@radenkozec thanks for verifying that the issue is still present. I've passed on details of this issue to folks on the SQL Client team so that they can investigate. They aren't on GitHub at the moment, so I'll keep this issue updated.

**Comment by rowanmiller** [comment]
@radenkozec can you share the code that you are getting the exception from?

**Comment by radenkozec** [comment]
@rowanmiller I am not able to share exact code but I am trying to pass List<T> as table valued parameter to SQL Server stored procedure.
Here is a similar code and exception is thrown in OrderHeaderCollection GetEnumerator:

Maybe I can do a workaround and dataTable instead of OrderHeaderCollection if DataTable works on .NET Core? 


public class OrderHeaderCollection : List<OrderHeader>, IEnumerable<SqlDataRecord>
{
  IEnumerator<SqlDataRecord> IEnumerable<SqlDataRecord>.GetEnumerator()
  {
    var sdr = new SqlDataRecord(
     new SqlMetaData("OrderId", SqlDbType.Int),
     new SqlMetaData("CustomerId", SqlDbType.Int),
     new SqlMetaData("OrderedAt", SqlDbType.Date));
 
    foreach (OrderHeader oh in this)
    {
      sdr.SetInt32(0, oh.OrderId);
      sdr.SetInt32(1, oh.CustomerId);
      sdr.SetDateTime(2, oh.OrderedAt);
 
      yield return sdr;
    }
  }
}
 


After this I am calling stored procedure and passing table valued parameter:


 public void AddUpdateItems(List<OrderHeader> items)
        {
            var collection = new OrderHeaderCollection();
            collection.AddRange(items);

            using (var conn = new SqlConnection(SqlHelper.GetConnectionString()))
            {
                var parameters = new[]
                {
                    new SqlParameter("@Items", SqlDbType.Structured)
                    {
                        Value = collection == null || collection.Count == 0 ? null : collection
                    }
                };
                SqlHelper.ExecuteNonQuery(conn, CommandType.StoredProcedure, "AddUpdate", parameters);
            }
        }

**Comment by rowanmiller** [comment]
@radenkozec I was just after some code to use to reproduce the issue to send to the SQL Client team. But in an app targeting CoreCLR the repro code is as simple as.

```csharp
new SqlMetaData("Test", System.Data.SqlDbType.Int);
```

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
