### ISSUE TITLE
404 And System.ArgumentNullException Downloading System.Runtime.Extensions in dnu restore

### ISSUE THREAD

**Issue by DylanDonkersgoed** [aspnet/Home#745]
After upgrading to beta5 I ran into an issue with dnu restore encountering a 404 when pulling in the package System.Runtime.Extensions v4.0.10-beta-22828. I didn't pull in this package manually, it's a dependency for something else. I'm not sure whether the issue was related to beta5 or if I just coincidentally noticed it then as switching the packages back to beta4 and using the beta4 dnvm does not fix the issue.

Here is a gist with the log, my project.json file and my NuGet.config file:
https://gist.github.com/DylanDonkersgoed/caca3ab545c9a4613fe0

The last dependency is a local class library which restores without issue.

**Comment by davidfowl** [comment]
Try `dnu restore --no-cache` from the command line. Like like your package cache is corrupted. BTW this should be fixed in later releases.

**Comment by DylanDonkersgoed** [comment]
Thank you for your response @davidfowl. I did try that a few times and it had no effect. I forgot to comment here but I did actually resolve the issue. It appeared to be related to a breaking change I missed between beta4 and beta5, specifically that the Microsoft.Framework.ConfigurationModel packages were now the Microsoft.Framework.Configuration packages.

I'm not sure why it still occurred when I switched back to beta4, perhaps this was related to a corrupted package cache. I can't remember if I did a full `dnu restore --no-cache` after switching back to beta4.
