### ISSUE TITLE
Publish does not respect Default setting for Target DNX Version

### ISSUE THREAD

**Issue by jderus** [aspnet/Home#908]
The basic scenario is switching your application to x64 when you realize your app pool is x64.
The expected steps:
1) Change global.json to x64
2) Open Publish dialogue
3) Verify that Publish dialogue Target DNX Version shows Default (%x64%)
4) Publish

The script output shows that it is passing the --runtime parameter as %x86%. The published approot runtime is %x86%.

However, if you explicitly set the Target DNX Version to %x64%, the script generates the correct --runtime and the approot runtime is also correct.

**Comment by vijayrkn** [comment]
This was a known issue in beta6 tooling (https://github.com/aspnet/Tooling/blob/master/known-issues.md). Publish tooling was not respecting the default target dnx version value displayed on the publish dialog. 

This is fixed in beta7 tooling - http://www.microsoft.com/en-us/download/details.aspx?id=48738

**Comment by jderus** [comment]
Thanks for the quick response. Sorry if I put the issue in the wrong place.
I couldn't verify the fix because Installing the beta7 tools and changing the global.json to beta7 resulted in a broken build.

Key error
Error	CS1703	Multiple assemblies with equivalent identity have been imported: '<in-memory assembly>' and '<in-memory assembly>'. Remove one of the duplicate references.

This looks to be a pseudo-regression in compatibility with EF6.1.3 to me, but I could be wrong.

**Comment by vijayrkn** [comment]
To verify this publish issue all you need is the beta7 tooling bits, you can continue to use the global.json pointing to beta6 runtime bits. 

If you still want to migrate your projects to beta7 runtime and if you are running into build issues, please open the issue in dnx repo (https://github.com/aspnet/dnx)

**Comment by jderus** [comment]
I am seeing some wonky behavior here, so I just cannot validate your fix. Sorry.
After upgrading to beta7 tooling via the link you supplied, here are my observations:

1) in global.json with sdk version= 1.0.0-beta5, the issue still repros.
2) there is no available x64 publish with 1.0.0-beta6.
3) changing to 1.0.0-beta7 regresses the local build ability as stated above.
4) reverting to 1.0.0-beta5 no longer builds (likely due to changes made to make 1.0.0-beta7 work).
5) I can no longer get Publish to recognize x64 as a default, no matter what global.json is set to.

I would probably have to restart the project from scratch and build it up piece by piece to get a reduced repro and move the issue to the dnx repo.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
